### ISSUE TITLE
Fortify ToDo List

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#132]
List of things still having to be done for Fortify:

- [ ] add some actual compositions
- [ ] secret keybind to deploy plastic chair
- [ ] action to redeploy/"edit" fortify objects after placing (later)
- [ ] switching backpacks should reset internal budget
- [ ] 3den/Zeus compat
    - [ ] turn object into container
    - [ ] create composition from selection
- [ ] quickly deployable riot shield for cover whily building fortifications

**Comment by m0kka** [comment]
not all done, but I'm content with it for now
