### ISSUE TITLE
Supplies Model Updates

### ISSUE THREAD

**Issue by m0kka** [Special-Operations-Brigade/SOB-Issue-Tracker#304]
Coinciding with #299 I will update the models of our supply crates, improve texture workflow for them etc

**Work Items:**

- [ ] New crate size structure: small / medium (currently "wide") / large (new model tbd)
- [x] Condense texture sets, better readability of supply type using colour stripes
- [ ] Make ViV compatible
